routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('index');
Route::resource('users', App\Http\Controllers\UsersController::class);
Route::resource('customers', App\Http\Controllers\CustomersController::class);
Route::get('contact', [App\Http\Controllers\ContactFormController::class, 'create'])->name('contact.create');
Route::post('contact', [App\Http\Controllers\ContactFormController::class, 'store'])->name('contact.store');
Route::view('about', 'about')->name('about');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    
    function roles(){
        return $this->belongsToMany(Role::class)
                ->withPivot(['role_assigned_by_id'])
                ->using(RoleUser::class)
                ->withTimestamps();
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Role;
use Illuminate\Http\Request;
use \Illuminate\Validation\Rule;

class UsersController extends Controller {

    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $users = User::with('roles')->paginate(10);

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $user  = new User();
        $roles = Role::all();

        return view('users.create', compact('user', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store() {
        $rules = $this->rules(['email' => 'unique:users']);
        $data  = request()->validate($rules);

        $user = User::create($data);
        $this->syncWithRolesValues($user, $data);

        return redirect()->route('users.show', [$user]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user) {
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user) {
        $roles         = Role::all();
        $user_role_ids = $user->roles->pluck('id')->toArray();

        return view('users.edit', compact('user', 'roles', 'user_role_ids'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(User $user) {
        $rules = $this->rules(['email' => Rule::unique('users')->ignore($user)]);
        if (!request()->filled('password')) {
            unset($rules['password']);
        }

        $data = request()->validate($rules);
        $user->update($data);
        $this->syncWithRolesValues($user, $data);

        return redirect()->route('users.show', [$user]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user) {
        $user->delete();

        return redirect()->route('users.index');
    }
    
    private function syncWithRolesValues($user, $data) {
        $user->roles()->syncWithPivotValues($data['roles'] ?? [], ['role_assigned_by_id' => auth()->user()->id]);
    }

    private function rules($actionRules) {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', $actionRules['email']],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'roles' => 'exists:roles,id',
        ];
    }

}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', __('users.create'))

@section('content')

<div class="row justify-content-center">
    <div class="col-8">
        <h1>{{ __('users.create') }}</h1>        
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-8">
        <form action="{{ route('users.store') }}" method="POST" enctype="multipart/form-data">
            @include('users.form')

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('users.create_button') }}
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', __('users.update') . ' ' . $user->name)

@section('content')

<div class="row justify-content-center">
    <div class="col-8">
        <h1>{{ __('users.update') . ' ' . $user->name }}</h1>        
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-8">
        <form action="{{ route('users.update', [$user]) }}" method="POST" enctype="multipart/form-data">
            @method('PATCH')
            @include('users.form')

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('users.update_button') }}
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/users/form.blade.php
@csrf
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('users.name') }}</label>

    <div class="col-md-6">
        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') ?? $user->name }}" autocomplete="name" autofocus>

        @error('name')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('users.email') }}</label>

    <div class="col-md-6">
        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') ?? $user->email }}" autocomplete="email">

        @error('email')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>
<div class="form-group row">
    <label for="roles" class="col-md-4 col-form-label text-md-right">{{ __('users.roles') }}</label>

    <div class="col-md-6">
        @foreach($roles as $role)
        <div class="form-check">
            <input id="role_{{ $role->id }}"
                   name="roles[]"
                   type="checkbox"
                   value="{{ $role->id }}"
                   class="form-check-input"
                   {{ (in_array($role->id, $user_role_ids) ? 'checked' : '') }} />
            <label class="form-check-label" for="role_{{ $role->id }}">{{ $role->name }}</label>

        </div>
        @endforeach
    </div>
</div>
<div class="form-group row">
    <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('users.password') }}</label>

    <div class="col-md-6">
        <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" autocomplete="new-password">

        @error('password')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('users.password_confirmation') }}</label>

    <div class="col-md-6">
        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" autocomplete="new-password">
    </div>
</div>

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', __('users.list'))

@section('content')

<div class="row">
    <div class="col-12">
        <h1>{{ __('users.list') }}</h1>
    </div>
</div>

<div class="row">
    <div class="col-12 py-1">
        <a href="{{ route('users.create') }}">{{ __('users.create') }}</a>
    </div>
</div>

<div class="container-fluid">

    <div class="row">
        <div class="col-1">
            #
        </div>
        <div class="col-3">
            Name
        </div>
        <div class="col-3">
            e-mail
        </div>
        <div class="col-1">
            Roles
        </div>
        <div class="col-2">
            updated at
        </div>
        <div class="col-2">
            created at
        </div>
    </div>
    @foreach($users as $user)
    <div class="row">
        <div class="col-1">
            {{ $user->id }}
        </div>
        <div class="col-3">
            <a href="{{ route('users.show', [$user]) }}">
                {{ $user->name }}
            </a>
        </div>
        <div class="col-3">
            {{ $user->email }}
        </div>
        <div class="col-1">
            @foreach($user->roles as $role)
                {{ $role->name }}
            @endforeach
        </div>
        <div class="col-2">
            {{ $user->updated_at }}
        </div>
        <div class="col-2">
            {{ $user->created_at }}
        </div>
    </div>
    @endforeach

    <div class="row">
        <div class="col-12 d-flex justify-content-center pt-4">
            {{ $users->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('title', __('users.show') . ' ' . $user->name)

@section('content')

<div class="row justify-content-center">
    <div class="col-8">
        <h1>{{ __('users.show') . ' ' . $user->name }}</h1>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-8">
        <div class="row">
            <div class="col-md-4 text-md-right">{{ __('users.name') }}:</div>
            <div class="col-md-6">{{ $user->name }}</div>
        </div>

        <div class="row">
            <div class="col-md-4 text-md-right">{{ __('users.email') }}:</div>
            <div class="col-md-6">{{ $user->email }}</div>
        </div>
    </div>
    <div class="col-8">
        <div class="row">
            <div class="col-md-4 text-md-right">{{ __('users.roles') }}:</div>
            <div class="col-md-6">
                @foreach($user->roles as $role)
                <div class="row">
                    <div class="col-md-12">
                        {{ $role->name }}, created by {{ $role->pivot->role_assigned_by->name }}
                    </div>
                </div>
                @endforeach
            </div>
        </div>

    </div>
</div>
<div class="row justify-content-center">
    <div class="col-md-4 d-flex pt-3">
        <div class="pr-1 w-50">
            <a class="btn btn-primary w-100" href="{{ route('users.edit', [$user]) }}">Edit</a>
        </div>
        <div class="pl-1 w-50">
            <form action="{{ route('users.destroy', [$user]) }}" method="POST">
                @method('DELETE')
                @csrf

                <button class="btn btn-danger w-100" type="submit">Delete</button>
            </form>
        </div>
    </div>
</div>
@endsection